language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools

  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install unidecode
  - travis_install_nightly


script:
  - travis_run_tests

after_success:
- travis_after_tests_success
